### ISSUE TITLE
Cannot run under any other than the hard-coded user ID

### ISSUE THREAD

**Issue by mirekphd** [bitnami/bitnami-docker-cassandra#111]
### Name and Version

bitnami/cassandra:4.0

### What steps will reproduce the bug?

The startup script fails to change user ID to e.g. 1234 (and in general to any high, non-root ID):
```
$ docker run -d --rm --name cassandra -v /tmp:/bitnami -u 1234 bitnami/cassandra:4.0 && docker logs -f cassandra
```

### What is the expected behavior?

... and the only way to run it specifying the user id is to use the hard-coded user 1001:
```
$ docker run -d --rm --name cassandra -v /tmp:/bitnami -u 1001 bitnami/cassandra:4.0 && docker logs -f cassandra
```

### What do you see instead?

... this error message:
```
WARN  [main] 2022-07-16 13:37:05,479 NativeLibrary.java:201 - Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK.
ERROR [COMMIT-LOG-ALLOCATOR] 2022-07-16 13:37:05,550 JVMStabilityInspector.java:167 - Exiting due to error while processing commit log during initialization.
org.apache.cassandra.io.FSWriteError: java.nio.file.AccessDeniedException: /bitnami/cassandra/data/commitlog/CommitLog-7-1657978625503.log
	at org.apache.cassandra.db.commitlog.CommitLogSegment.<init>(CommitLogSegment.java:181)
	at org.apache.cassandra.db.commitlog.MemoryMappedSegment.<init>(MemoryMappedSegment.java:45)
	at org.apache.cassandra.db.commitlog.CommitLogSegment.createSegment(CommitLogSegment.java:138)
	at org.apache.cassandra.db.commitlog.CommitLogSegmentManagerStandard.createSegment(CommitLogSegmentManagerStandard.java:66)
	at org.apache.cassandra.db.commitlog.AbstractCommitLogSegmentManager$1.runMayThrow(AbstractCommitLogSegmentManager.java:115)
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.nio.file.AccessDeniedException: /bitnami/cassandra/data/commitlog/CommitLog-7-1657978625503.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.apache.cassandra.db.commitlog.CommitLogSegment.<init>(CommitLogSegment.java:176)
	... 7 common frames omitted
```

### Additional information

This inability to run under arbitrary user ID is a blocker for Openshift and OKD deployments (where such ID changes are obligatory).

**Comment by joancafom** [comment]
Hi @mirekphd 

I'm sorry, but I am unable to reproduce your issue locally. I believe the error you are experiencing is related to the permissions of the mapped volume (could it be that `/tmp` has some strange permissions configured?).

This is the `docker-compose.yaml` file I am using:

```yaml
version: '2'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    user: "1234"
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
volumes:
  cassandra_data:
    driver: local
```

```bash
$ docker-compose up
$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS          PORTS                                            NAMES
b54e1cca0e52   bitnami/cassandra:4.0   "/opt/bitnami/script…"   7 minutes ago    Up 7 minutes    0.0.0.0:7000->7000/tcp, 0.0.0.0:9042->9042/tcp   bitnami-docker-cassandra_cassandra_1
```

Could you please try with this configuration instead to discard any issues related to the mapped volumes?

**Comment by mirekphd** [comment]
While the solution above was designed to avoid persisting data outside of the container, I'm grateful for the suggestion to disregard issues related to the mapped volumes (which I took as a suggestion that the issue was caused by a user error in volume mapping:). And this was it! It is not a hard-coded user or a root requirement after all, but a conflict of user IDs between the external and internal users: the container user (here: 1234) did not have permissions to write data to the external folder mapped onto the host, which I admit caught me off guard, that the `/tmp` folder should be so well hardened in CentOS Stream - in Ubuntu it would most likely work (where the whole purpose of this folder is being [writeable by anybody](https://unix.stackexchange.com/a/71625/448081)).

The external data folder prep that was required before running the container:
```
$ mkdir -p /tmp/cassandra_data && sudo chown 1234:0 /tmp/cassandra_data && sudo chmod ug+rwx /tmp/cassandra_data
```

Running the container under arbitrary user 1234 - this time successfully:
```
$ docker run -d --rm --name cassandra_new -v /tmp/cassandra_data:/bitnami -u 1234 -p 7002:7000 -p 9044:9042 bitnami/cassandra:4.0 && docker logs -f cassandra_new
```

Verifying container user UID and that data was persisted outside of the container:
```
$ docker exec -it cassandra_new bash

$ id
uid=1234 gid=0(root) groups=0(root)

$ ls -lant /bitnami/cassandra/data/
total 0
drwxr-xr-x 7 1234 0 107 Jul 19 12:10 data
drwxr-xr-x 2 1234 0  80 Jul 19 12:10 commitlog
drwxr-xr-x 6 1234 0  68 Jul 19 12:10 .
drwxr-xr-x 2 1234 0   6 Jul 19 12:10 hints
drwxr-xr-x 2 1234 0   6 Jul 19 12:10 saved_caches
drwxr-xr-x 3 1234 0  18 Jul 19 12:10 ..

$ exit
exit

[mir@build-srv-fi cassandra]$ ls -lant /tmp/cassandra_data/cassandra/data/
total 0
drwxr-xr-x 7 1234 0 107 Jul 19 14:10 data
drwxr-xr-x 2 1234 0  80 Jul 19 14:10 commitlog
drwxr-xr-x 6 1234 0  68 Jul 19 14:10 .
drwxr-xr-x 2 1234 0   6 Jul 19 14:10 hints
drwxr-xr-x 2 1234 0   6 Jul 19 14:10 saved_caches
drwxr-xr-x 3 1234 0  18 Jul 19 14:10 ..
```

**Comment by mirekphd** [comment]
Thanks @joancafom for help in solving the issue!
