### ISSUE TITLE
Busy pool exception

### ISSUE THREAD

**Issue by pratapagiri** [bitnami/bitnami-docker-cassandra#65]
When running Cassandra 3.11.6 docker with multiple springboot services, getting below exception:

Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra/172.20.0.2:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [cassandra/172.20.0.2] Pool is busy (no available connection and timed out after 5000 MILLISECONDS)))
at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:230)
at com.datastax.driver.core.RequestHandler.access$1000(RequestHandler.java:50)
at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:301)
at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:368)
at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:53)
at com.datastax.driver.core.HostConnectionPool$PendingBorrow$1.run(HostConnectionPool.java:694)
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)

Is there any environment setting that can be used to resolve this issue?

- Output of `docker info`:

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 64
  Running: 50
  Paused: 0
  Stopped: 14
 Images: 184
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 20.27GiB
 Name: docker-desktop
 ID: BQQU:633N:XK3N:LGVY:VT4Y:IILZ:VJJK:PD3M:5ZOT:X4F4:J5MG:NVD6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 426
  Goroutines: 410
  System Time: 2020-03-17T17:30:57.927465528Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Comment by rafariossaa** [comment]
Hi @pratapagiri ,
  I am not a cassandra expert but it seems that the connection pool was exhausted and you need limit the number of connections in your application.
  Maybe this [link](https://docs.datastax.com/en/developer/java-driver/3.1/manual/pooling/)  would be helpful.
