### ISSUE TITLE
BusyPoolException with OperationTimedOutException

### ISSUE THREAD

**Issue by yogeshbidari** [bitnami/bitnami-docker-cassandra#77]
**Description**

We are facing issue with my cassandra cluster, we are observing connection timeout errors with BusyPoolException.
Cassandra connections are timingout.

**Describe the results you received:**

Connection timeout errors and queries are not ruuning.

**Describe the results you expected:**

Should handle all the connection

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

cassandra version: 3.11.3
GKE version 1.14.10

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using GCP GKE for the k8s cluster deployment.

Assigned resource request and limits
```
Requests:
 -cpu: 3
 -memory: 15GB
Limits:
 -cpu: 6
 -memory: 30GB
```
**LOGS**

```
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /x.x.x.x:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/x.x.x.x:9042] Timed out waiting for server response), cassandra/x.x.x.x:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [cassandra/x.x.x.x:9042] Pool is busy (no available connection and the queue has reached its max size 0)))
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:513)
	at akka.persistence.cassandra.package$ListenableFutureConverter$$anon$2.$anonfun$run$2(package.scala:50)
	at scala.util.Try$.apply(Try.scala:213)
	at akka.persistence.cassandra.package$ListenableFutureConverter$$anon$2.run(package.scala:50)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /x.x.x.x:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/x.x.x.x:9042] Timed out waiting for server response), cassandra/x.x.x.x:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [cassandra/x.x.x.x:9042] Pool is busy (no available connection and the queue has reached its max size 0)))
	at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:283)
	at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:61)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:375)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:444)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1015)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1137)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:707)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:112)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:996)
	at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:112)
	at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:100)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.query(RequestHandler.java:400)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:359)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.retry(RequestHandler.java:557)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.processRetryDecision(RequestHandler.java:539)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:981)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1605)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by andresbono** [comment]
Hi @yogeshbidari, can you give us more information about how are you deploying the Cassandra cluster in k8s?

**Comment by yogeshbidari** [comment]
We are using yaml file to deploy.

`apiVersion: v1
kind: Service
metadata:
   name: cassandra
   labels:
      service: cassandra
spec:
   clusterIP: None
   ports:
     - name: intra
       port: 7000
       targetPort: intra
     - name: tls
       port: 7001
       targetPort: tls
     - name: jmx
       port: 7199
       targetPort: jmx
     - name: cql
       port: 9042
       targetPort: cql
     - name: thrift
       port: 9160
       targetPort: thrift
   publishNotReadyAddresses: true
   selector:
      service: cassandra
   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
   name: cassandra-ui   
   labels:
      service: cassandra
spec:
   externalTrafficPolicy: Cluster
   ports:
     - name: cql
       nodePort: 30212
       port: 9042
       targetPort: cql
     - name: thrift
       nodePort: 30213
       port: 9160
       targetPort: thrift
   selector:
      service: cassandra
   type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: cassandra
   labels:
      service: cassandra
spec:
   serviceName: cassandra
   replicas: 3
   updateStrategy:
      type: OnDelete
   selector:
      matchLabels:
         service: cassandra
   template:
      metadata:
         labels:
            service: cassandra
      spec:
         terminationGracePeriodSeconds: 120
         containers:
            - name: cassandra
              image: bitnami/cassandra:3.11.3
              imagePullPolicy: Always
              ports:
                - name: intra
                  containerPort: 7000
                - name: tls
                  containerPort: 7001
                - name: jmx
                  containerPort: 7199
                - name: cql
                  containerPort: 9042
                - name: thrift
                  containerPort: 9160
              env:
                - name: CASSANDRA_CLUSTER_NAME
                  value: cassandra
                - name: CASSANDRA_SEEDS
                  value: cassandra-0.cassandra.default.svc.cluster.local,cassandra-1.cassandra.default.svc.cluster.local,cassandra-2.cassandra.default.svc.cluster.local
                - name: CASSANDRA_PASSWORD
                  value: xxxxxxx
                - name: POD_IP
                  valueFrom:
                     fieldRef:
                        apiVersion: v1
                        fieldPath: status.podIP
                - name: CASSANDRA_NUM_TOKENS
                  value: "256"
                - name: CASSANDRA_DATACENTER
                  value: dc1
                - name: CASSANDRA_ENDPOINT_SNITCH
                  value: SimpleSnitch
                - name: CASSANDRA_RACK
                  value: rack1
                - name: CASSANDRA_ENABLE_RPC
                  value: "true"
				- name: BITNAMI_DEBUG
                  value: "true"
              livenessProbe:
                 exec:
                    command:
                       - /bin/sh
                       - -c
                       - nodetool status
                 failureThreshold: 5
                 initialDelaySeconds: 60
                 periodSeconds: 30
                 successThreshold: 1
                 timeoutSeconds: 5
              readinessProbe:
                 exec:
                    command:
                       - /bin/sh
                       - -c
                       - nodetool status | grep -E "^UN\s+${POD_IP}"
                 failureThreshold: 5
                 initialDelaySeconds: 60
                 periodSeconds: 10
                 successThreshold: 1
                 timeoutSeconds: 5
              command:
                 - bash
                 - -ec
                 - |
                   if [[ $HOSTNAME =~ (.*)-0$ ]]; then
                     export CASSANDRA_PASSWORD_SEEDER=yes
                   else
                     export CASSANDRA_IGNORE_INITDB_SCRIPTS=1
                   fi
                   /app-entrypoint.sh /run.sh`

**Comment by andresbono** [comment]
Thanks. In addition to the statefulset, you are also deploying a service to have the pod accesible, right?

**Comment by yogeshbidari** [comment]
Yes. We are using loadbalancer service for external access.

apiVersion: v1
kind: Service
metadata:
   name: cassandra
   labels:
      service: cassandra
spec:
   clusterIP: None
   ports:
     - name: intra
       port: 7000
       targetPort: intra
     - name: tls
       port: 7001
       targetPort: tls
     - name: jmx
       port: 7199
       targetPort: jmx
     - name: cql
       port: 9042
       targetPort: cql
     - name: thrift
       port: 9160
       targetPort: thrift
   publishNotReadyAddresses: true
   selector:
      service: cassandra
   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
   name: cassandra-ui   
   labels:
      service: cassandra
spec:
   externalTrafficPolicy: Cluster
   ports:
     - name: cql
       nodePort: 30212
       port: 9042
       targetPort: cql
     - name: thrift
       nodePort: 30213
       port: 9160
       targetPort: thrift
   selector:
      service: cassandra
   type: LoadBalancer

**Comment by andresbono** [comment]
Hi @yogeshbidari, we couldn't reproduce your issue yet.

In order to deploy Cassandra in k8s, we recommend using the Helm Chart that we maintain: https://github.com/bitnami/charts/tree/master/bitnami/cassandra. Did you take a look? You might find it useful.
